name: FreeBSD-14-amd64

on:
  push:
    branches:
      - github_actions_FreeBSD

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        uses: cross-platform-actions/action@v0.26.0
        with:
          operating_system: freebsd
          version: '14.2'
          run: |
            uname -a
            echo $SHELL
            pwd
            ls -lah
            whoami
            env | sort
            sudo env ASSUME_ALWAYS_YES=yes pkg install -y at-spi2-core boost-libs cairo cereal cgal curl dbus expat gdk-pixbuf2 gettext-runtime gettext-tools glew glib gmp gtk3 harfbuzz hidapi Imath jpeg-turbo libbgcode libGLU libglvnd libiconv mpfr nlopt onetbb opencascade openvdb pango pkgconf png qhull tiff wx32-gtk3 xorgproto
            pkg info | wc -l
            pkg info | sort
